import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/providers/theme-provider"
import { ModalProvider } from '@/components/providers/modal-provider'
import { cn } from "@/lib/utils"
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import { SProvider } from '@/components/providers/session-provider'
import { ToastProvider } from '@/components/ui/toast' 
import { Toast } from '@/components/ui/toast'
import { Navbar } from '@/components/navbar'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Space Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode,
  authModal: React.ReactNode
}) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="space-theme">
          <SocketProvider>
            <ModalProvider />
            <QueryProvider>
              <SProvider>
                <Navbar />
                {authModal}
                {children}
              </SProvider>
            </QueryProvider>
          </SocketProvider>
        </ThemeProvider>
        <ToastProvider>
          <Toast />
        </ToastProvider>
      </body>
    </html>
  )
}
